apiVersion: apps/v1
kind: Deployment 
metadata:
  name: stress
spec:
  replicas: 1
  selector:
    matchLabels:
      project: stress
  template:
    metadata:
      labels:
        project: stress
    spec:
      containers:
        - name: stress
          image: rebrainme/stress
          ports:
          - containerPort: 80
          resources:
            limits:
              memory: 128Mi # Ограничение на использование Памяти
          readinessProbe: # Проверка приложения на принятие трафика
            failureThreshold: 5
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            successThreshold: 2
            timeoutSeconds: 3

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler # Развёртывание HPA
metadata:
  name: my-autoscalling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: stress-deployment-autoscaling
  minReplicas: 1 
  maxReplicas: 4 # Ограничение использования Подов до 4-ёх.
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: AverageValue
        averageValue: 0.1 # Среднее значение использования CPU.
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80 # Если CPU привысит 80% , то начнётся создание Подов
